### ISSUE TITLE
Does not Work With Java 7

### ISSUE THREAD

**Issue by jeffdc** [gradle/gradle-jdocbook#12]
On Java 7 (Linux 64bit 1.7.0_06-b24) all of the unit tests fail with a NullPointerException. If I switch to Java 1.6 all is well. I spent a bit of time trying to chase this, but I do not have a reliable Groovy dev environment set up and was spending all of my time [Yak Shaving](http://en.wiktionary.org/wiki/yak_shaving).

Here is the stack trace:

```
org.gradle.api.GradleScriptException: A problem occurred evaluating script.
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:82)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
    at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:840)
    at org.jboss.gradle.plugins.jdocbook.test.AbstractJDocbookSpock.applyScript(AbstractJDocbookSpock.groovy:59)
    at org.jboss.gradle.plugins.jdocbook.test.SingleJDocbookSpock.check if tasks are well configured(SingleJDocbookSpock.groovy:37)
Caused by: java.lang.NullPointerException
    at org.jboss.gradle.plugins.jdocbook.book.Book.format(Book.groovy:96)
    at org.jboss.gradle.plugins.jdocbook.book.Book.format(Book.groovy:92)
    at org.jboss.gradle.plugins.jdocbook.JDocBookConvention.format(JDocBookConvention.groovy)
    at org.jboss.gradle.plugins.jdocbook.JDocBookConvention.invokeMethod(JDocBookConvention.groovy)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:102)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:99)
    at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
    at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.groovy:73)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
    at groovy.lang.Script.invokeMethod(Script.java:78)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:102)
    at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:61)
    at default_6nj8h1djh777vgcvbrd732gpg.run_closure1(/home/jeff/boxes/gradle-jdocbook/build/resources/test/scripts/default.gradle:34)
    at groovy.lang.Closure.call(Closure.java:412)
    at groovy.lang.Closure.call(Closure.java:425)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:141)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:90)
    at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:56)
    at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
    at org.jboss.gradle.plugins.jdocbook.JDocBookConvention.jdocbook(JDocBookConvention.groovy:82)
    at org.jboss.gradle.plugins.jdocbook.JDocBookConvention.invokeMethod(JDocBookConvention.groovy)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:102)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:99)
    at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
    at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.groovy:73)
    at default_6nj8h1djh777vgcvbrd732gpg.run(/home/jeff/boxes/gradle-jdocbook/build/resources/test/scripts/default.gradle:31)
    ... 5 more
```

**Comment by sebersole** [comment]
https://github.com/gradle/gradle-jdocbook/pull/13

**Comment by sebersole** [comment]
Strong, could you take a look at this?  I don't know the Spock stuff

**Comment by stliu** [comment]
it seems JDK dependent, this only occurs on openjdk

patch applied, thanks
